# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  licenseplist-3_27_1-darwin = {
    pname = "licenseplist-3_27_1-darwin";
    version = "3.27.1";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.27.1/portable_licenseplist.zip";
      sha256 = "sha256-oCBAypheTrovfKGJxgxFiACWk9zbZwIaA/MEmL+CA7U=";
    };
  };
}
