# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  licenseplist-3_25_0-darwin = {
    pname = "licenseplist-3_25_0-darwin";
    version = "3.25.0";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.25.0/portable_licenseplist.zip";
      sha256 = "sha256-H79jaa4KODPb4qGEDwHoa/Ndyj8U0z+RyowkvnS/ayk=";
    };
  };
  licenseplist-3_25_1-darwin = {
    pname = "licenseplist-3_25_1-darwin";
    version = "3.25.1";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.25.1/portable_licenseplist.zip";
      sha256 = "sha256-oxbarHYUyZ34kN5bUC1EHs/SWG7snjMS2pUOUtnr1AU=";
    };
  };
  licenseplist-3_26_0-darwin = {
    pname = "licenseplist-3_26_0-darwin";
    version = "3.26.0";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.26.0/portable_licenseplist.zip";
      sha256 = "sha256-QRSwM1cw6DER+RMfiY8YmD5IbvlGoQhpg/3b7AwROK4=";
    };
  };
  licenseplist-3_27_0-darwin = {
    pname = "licenseplist-3_27_0-darwin";
    version = "3.27.0";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.27.0/portable_licenseplist.zip";
      sha256 = "sha256-i7HdLF8sUEy/GmvaqAAVFpxR8mh0hBxBkRz6ti2QIU4=";
    };
  };
  licenseplist-3_27_1-darwin = {
    pname = "licenseplist-3_27_1-darwin";
    version = "3.27.1";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.27.1/portable_licenseplist.zip";
      sha256 = "sha256-oCBAypheTrovfKGJxgxFiACWk9zbZwIaA/MEmL+CA7U=";
    };
  };
  licenseplist-3_27_2-darwin = {
    pname = "licenseplist-3_27_2-darwin";
    version = "3.27.2";
    src = fetchurl {
      url = "https://github.com/mono0926/LicensePlist/releases/download/3.27.2/portable_licenseplist.zip";
      sha256 = "sha256-v+FeIbRxHwvD5xK4IDff9fdXbPssDNtRovOKOevV26Q=";
    };
  };
}
